### ISSUE TITLE
Rework Permissions: grantTeamPermissions.

### ISSUE THREAD

**Issue by JoshuaMitchell** [gpsimpact/census-relational-organizing-backend#119]
We should rename grantTeamPermissions to toggleTeamPermission.

Mutation should take current permission and toggle it to input value.

**Comment by jakelowen** [comment]
@JoshuaMitchell - Remind me:  The intention here is that there are defined roles within a team:

- ADMIN
- MEMBER
- APPLICANT 
- etc

And that a user should have one and only one role at a time.  So if a user is toggled to an admin, they will no longer be a "member".  Is that right?
