### ISSUE TITLE
Login flow: unauthed not required for confirmLogin

### ISSUE THREAD

**Issue by jrazmi** [gpsimpact/census-relational-organizing-backend#191]
Confirm Login mutation should reissue a valid request rather than throwing a graphql already authed error.

**Comment by jakelowen** [comment]
I think I can meet you halfway here, but it would be very complicated to completely reissue. Confirm Login tokens are single use and "self destructing". Once you click on the link, it is no longer possible to extract the user from the token.  So I can't really "reissue" a login token.

BUT..  I can (and have) removed the requiresNonAuth shield rule. So if you attempt to confirmLogin with a nonsense OR an expired token it no longer throws an error, just returns a success: false response:

```
  const userId = await context.dataSource.user.getLoginToken(args.token);
  if (!userId) {
    return {
      code: "DOES_NOT_EXIST",
      success: false,
      message: "This token is either invalid or expired!"
    };
  }
```

Can you do something with that response @jrazmi ?

Pushing up this non-error revision now.
