### ISSUE TITLE
Offset on queries

### ISSUE THREAD

**Issue by JoshuaMitchell** [gpsimpact/census-relational-organizing-backend#80]
Might just be an issue I'm having - but @jakelowen can you take a look when you get a minute.

The offset on teams queries doesn't seem to be working. Checked in the playground as well.
Regardless of offset in the input its pulling the first record.

**Comment by jakelowen** [comment]
I think I closed this with an update with 0.4.4 update of https://github.com/jakelowen/sqorn-graphql-filters
