### ISSUE TITLE
Public Teams/Team Queries

### ISSUE THREAD

**Issue by JoshuaMitchell** [gpsimpact/census-relational-organizing-backend#86]
@jakelowen I'm still getting a authorization required on the teams/team queries for the public route.  only trying to pull id, name, description, slug.

Can you verify that a completely anon user can make that on teams/team endpoints?
OR can you breakoff a new public teams/team query?

`import { gql } from "apollo-boost";

export const GET_TEAMS_PUBLIC_QUERY = gql`
    query getTeamsPublic($input: TeamsInput){
        teams(input:$input){
            hasMore
            totalCount
            items {
                id
                name
                description
                slug
            }
        }
    }
`;`

**Comment by jakelowen** [comment]
@JoshuaMitchell - I think this should be resolved. now. Please reopen if not.
